In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('OUT 1-2 data(categorial values encoded).csv')
df

CountryName CountryCode  Population growth  Total population  \
0        Brazil         BRA           0.817556      2.076529e+08   
1   Switzerland         CHE           1.077221      8.372098e+06   
2       Germany         DEU           1.193867      8.266768e+07   
3       Denmark         DNK           0.834638      4.998162e+06   
4         Spain         ESP          -0.008048      4.644396e+07   
5        France         FRA           0.407491      6.689611e+07   
6         Japan         JPN          -0.115284      1.269945e+08   
7        Greece         GRC          -0.687543      1.074674e+07   
8          Iran         IRN           1.148789      8.027743e+07   
9        Kuwait         KWT           2.924206      4.052584e+06   
10      Morocco         MAR           0.046349      3.527679e+07   
11      Nigeria         NGA           2.619034      1.859896e+08   
12        Qatar         QAT           3.495070      2.569804e+06   
13       Sweden         SWE           0.408105      9.903122e+06   
14        India         IND           1.148215      1.324171e+09   

    Area (sq. km)  Coronavirus Cases    A    B    C  
0    8.358140e+06              59324  0.0  1.0  0.0  
1    3.951600e+04              29061  0.0  1.0  0.0  
2    3.489000e+05             156727  1.0  0.0  0.0  
3    4.226200e+04               8575  0.0  1.0  0.0  
4    5.002100e+05             223759  1.0  0.0  0.0  
5    5.475570e+05             161488  1.0  0.0  0.0  
6    3.645600e+05              13231  0.0  1.0  0.0  
7    1.289000e+05               2506  0.0  0.0  1.0  
8    1.628760e+06              90481  0.0  0.0  0.0  
9    3.112933e+04               3075  0.0  0.0  1.0  
10   4.463000e+05               4047  0.0  0.0  1.0  
11   9.107700e+05               1182  0.0  0.0  0.0  
12   1.161000e+04              10287  0.0  1.0  0.0  
13   4.073100e+05              18640  0.0  0.0  1.0  
14   2.973190e+06              26917  0.0  1.0  0.0

In [3]:
from sklearn.preprocessing import MinMaxScaler,Normalizer,StandardScaler

In [4]:
pop_growth=np.array(df['Population growth'])
pop_growth

array([ 0.81755571,  1.07722117,  1.19386676,  0.83463761, -0.00804809,
        0.40749104, -0.11528418, -0.68754255,  1.1487886 ,  2.92420619,
        0.04634899,  2.61903353,  3.49506992,  0.40810541,  1.14821469])

In [5]:
scale1 = MinMaxScaler(feature_range=(0, 1))
new_pop_growth = scale1.fit_transform(pop_growth[:, np.newaxis])
new_pop_growth

array([[0.35984645],
       [0.42192857],
       [0.44981679],
       [0.36393048],
       [0.16245695],
       [0.26180613],
       [0.13681841],
       [0.        ],
       [0.43903928],
       [0.86351503],
       [0.17546248],
       [0.79055282],
       [1.        ],
       [0.26195302],
       [0.43890206]])

In [6]:
population = np.array(df['Total population'])
population

array([2.07652865e+08, 8.37209800e+06, 8.26676850e+07, 4.99816200e+06,
       4.64439590e+07, 6.68961090e+07, 1.26994511e+08, 1.07467400e+07,
       8.02774280e+07, 4.05258400e+06, 3.52767860e+07, 1.85989640e+08,
       2.56980400e+06, 9.90312200e+06, 1.32417135e+09])

In [7]:
new_population = scale1.fit_transform(population[:, np.newaxis])
new_population

array([[0.15517768],
       [0.00439035],
       [0.06060668],
       [0.00183744],
       [0.03319772],
       [0.04867299],
       [0.09414691],
       [0.00618714],
       [0.05879807],
       [0.00112196],
       [0.02474799],
       [0.13878603],
       [0.        ],
       [0.00554881],
       [1.        ]])

In [8]:
area = np.array(df['Area (sq. km)'])
area

array([8358140.        ,   39516.        ,  348900.        ,
         42262.        ,  500210.        ,  547557.        ,
        364560.        ,  128900.        , 1628760.        ,
         31129.33333333,  446300.        ,  910770.        ,
         11610.        ,  407310.        , 2973190.        ])

In [9]:
new_area = scale1.fit_transform(area[:, np.newaxis])
new_area

array([[1.        ],
       [0.00334343],
       [0.04041081],
       [0.00367242],
       [0.0585393 ],
       [0.06421195],
       [0.04228703],
       [0.01405255],
       [0.19375118],
       [0.00233862],
       [0.05208033],
       [0.1077286 ],
       [0.        ],
       [0.04740892],
       [0.35482769]])

In [10]:
data1 = df.copy()
data1['Population growth'] = new_pop_growth
data1['Total population'] = new_population
data1['Area (sq. km)'] = new_area
data1

CountryName CountryCode  Population growth  Total population  \
0        Brazil         BRA           0.359846          0.155178   
1   Switzerland         CHE           0.421929          0.004390   
2       Germany         DEU           0.449817          0.060607   
3       Denmark         DNK           0.363930          0.001837   
4         Spain         ESP           0.162457          0.033198   
5        France         FRA           0.261806          0.048673   
6         Japan         JPN           0.136818          0.094147   
7        Greece         GRC           0.000000          0.006187   
8          Iran         IRN           0.439039          0.058798   
9        Kuwait         KWT           0.863515          0.001122   
10      Morocco         MAR           0.175462          0.024748   
11      Nigeria         NGA           0.790553          0.138786   
12        Qatar         QAT           1.000000          0.000000   
13       Sweden         SWE           0.261953          0.005549   
14        India         IND           0.438902          1.000000   

    Area (sq. km)  Coronavirus Cases    A    B    C  
0        1.000000              59324  0.0  1.0  0.0  
1        0.003343              29061  0.0  1.0  0.0  
2        0.040411             156727  1.0  0.0  0.0  
3        0.003672               8575  0.0  1.0  0.0  
4        0.058539             223759  1.0  0.0  0.0  
5        0.064212             161488  1.0  0.0  0.0  
6        0.042287              13231  0.0  1.0  0.0  
7        0.014053               2506  0.0  0.0  1.0  
8        0.193751              90481  0.0  0.0  0.0  
9        0.002339               3075  0.0  0.0  1.0  
10       0.052080               4047  0.0  0.0  1.0  
11       0.107729               1182  0.0  0.0  0.0  
12       0.000000              10287  0.0  1.0  0.0  
13       0.047409              18640  0.0  0.0  1.0  
14       0.354828              26917  0.0  1.0  0.0

In [11]:
scale2=StandardScaler()
new_pop_growth = scale2.fit_transform(pop_growth[:, np.newaxis])
new_pop_growth

array([[-0.17853398],
       [ 0.04973637],
       [ 0.15227881],
       [-0.16351739],
       [-0.90431734],
       [-0.53901939],
       [-0.99858795],
       [-1.50165686],
       [ 0.11265087],
       [ 1.67340986],
       [-0.8564972 ],
       [ 1.40513439],
       [ 2.17525275],
       [-0.53847929],
       [ 0.11214635]])

In [12]:
new_population = scale2.fit_transform(population[:, np.newaxis])
new_population

array([[ 0.19052536],
       [-0.43001608],
       [-0.19866666],
       [-0.4405222 ],
       [-0.31146391],
       [-0.24777785],
       [-0.06063712],
       [-0.42262167],
       [-0.20610969],
       [-0.44346664],
       [-0.34623743],
       [ 0.12306813],
       [-0.44808387],
       [-0.42524862],
       [ 3.66725823]])

In [13]:
new_area = scale2.fit_transform(area[:, np.newaxis])
new_area

array([[ 3.48732066],
       [-0.51832861],
       [-0.3693516 ],
       [-0.51700634],
       [-0.29649161],
       [-0.27369271],
       [-0.36181087],
       [-0.47528773],
       [ 0.24693666],
       [-0.52236703],
       [-0.32245078],
       [-0.09879553],
       [-0.53176613],
       [-0.34122555],
       [ 0.89431717]])

In [14]:
data2 = df.copy()
data2['Population growth'] = new_pop_growth
data2['Total population'] = new_population
data2['Area (sq. km)'] = new_area
data2

CountryName CountryCode  Population growth  Total population  \
0        Brazil         BRA          -0.178534          0.190525   
1   Switzerland         CHE           0.049736         -0.430016   
2       Germany         DEU           0.152279         -0.198667   
3       Denmark         DNK          -0.163517         -0.440522   
4         Spain         ESP          -0.904317         -0.311464   
5        France         FRA          -0.539019         -0.247778   
6         Japan         JPN          -0.998588         -0.060637   
7        Greece         GRC          -1.501657         -0.422622   
8          Iran         IRN           0.112651         -0.206110   
9        Kuwait         KWT           1.673410         -0.443467   
10      Morocco         MAR          -0.856497         -0.346237   
11      Nigeria         NGA           1.405134          0.123068   
12        Qatar         QAT           2.175253         -0.448084   
13       Sweden         SWE          -0.538479         -0.425249   
14        India         IND           0.112146          3.667258   

    Area (sq. km)  Coronavirus Cases    A    B    C  
0        3.487321              59324  0.0  1.0  0.0  
1       -0.518329              29061  0.0  1.0  0.0  
2       -0.369352             156727  1.0  0.0  0.0  
3       -0.517006               8575  0.0  1.0  0.0  
4       -0.296492             223759  1.0  0.0  0.0  
5       -0.273693             161488  1.0  0.0  0.0  
6       -0.361811              13231  0.0  1.0  0.0  
7       -0.475288               2506  0.0  0.0  1.0  
8        0.246937              90481  0.0  0.0  0.0  
9       -0.522367               3075  0.0  0.0  1.0  
10      -0.322451               4047  0.0  0.0  1.0  
11      -0.098796               1182  0.0  0.0  0.0  
12      -0.531766              10287  0.0  1.0  0.0  
13      -0.341226              18640  0.0  0.0  1.0  
14       0.894317              26917  0.0  1.0  0.0

In [15]:
scale3=Normalizer(norm='l2')
new_pop_growth = scale3.fit_transform([pop_growth])
new_pop_growth

array([[ 0.1381221 ,  0.18199133,  0.20169804,  0.14100801, -0.00135969,
         0.06884365, -0.01947671, -0.116157  ,  0.19408231,  0.49403057,
         0.00783044,  0.44247311,  0.59047524,  0.06894745,  0.19398535]])

In [16]:
new_population = scale3.fit_transform([population])
new_population

array([[0.15190135, 0.00612432, 0.06047272, 0.00365623, 0.03397449,
        0.04893556, 0.09289849, 0.00786141, 0.05872421, 0.00296453,
        0.02580553, 0.13605436, 0.00187985, 0.00724429, 0.96865227]])

In [17]:
new_area = scale3.fit_transform([area])
new_area

array([[0.91537855, 0.00432777, 0.03821132, 0.00462851, 0.0547827 ,
        0.05996812, 0.0399264 , 0.01411705, 0.17838083, 0.00340927,
        0.04887851, 0.09974699, 0.00127152, 0.04460835, 0.32562201]])

In [18]:
data3 = df.copy()
data3['Population growth'] = new_pop_growth.T
data3['Total population'] = new_population.T
data3['Area (sq. km)'] = new_area.T
data3

CountryName CountryCode  Population growth  Total population  \
0        Brazil         BRA           0.138122          0.151901   
1   Switzerland         CHE           0.181991          0.006124   
2       Germany         DEU           0.201698          0.060473   
3       Denmark         DNK           0.141008          0.003656   
4         Spain         ESP          -0.001360          0.033974   
5        France         FRA           0.068844          0.048936   
6         Japan         JPN          -0.019477          0.092898   
7        Greece         GRC          -0.116157          0.007861   
8          Iran         IRN           0.194082          0.058724   
9        Kuwait         KWT           0.494031          0.002965   
10      Morocco         MAR           0.007830          0.025806   
11      Nigeria         NGA           0.442473          0.136054   
12        Qatar         QAT           0.590475          0.001880   
13       Sweden         SWE           0.068947          0.007244   
14        India         IND           0.193985          0.968652   

    Area (sq. km)  Coronavirus Cases    A    B    C  
0        0.915379              59324  0.0  1.0  0.0  
1        0.004328              29061  0.0  1.0  0.0  
2        0.038211             156727  1.0  0.0  0.0  
3        0.004629               8575  0.0  1.0  0.0  
4        0.054783             223759  1.0  0.0  0.0  
5        0.059968             161488  1.0  0.0  0.0  
6        0.039926              13231  0.0  1.0  0.0  
7        0.014117               2506  0.0  0.0  1.0  
8        0.178381              90481  0.0  0.0  0.0  
9        0.003409               3075  0.0  0.0  1.0  
10       0.048879               4047  0.0  0.0  1.0  
11       0.099747               1182  0.0  0.0  0.0  
12       0.001272              10287  0.0  1.0  0.0  
13       0.044608              18640  0.0  0.0  1.0  
14       0.325622              26917  0.0  1.0  0.0

In [19]:
data2.to_csv('OUT 1-3 data(standard-transformed).csv', index=False)